name: Deploy to EC2

on:
  push:
    branches:
      - main   # Deploy khi có push lên nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/charityrun
            git pull origin main
            sudo rm -rf /var/www/html/*
            sudo cp -r ~/charityrun/* /var/www/html/
            sudo systemctl restart nginx
          EOF
